# Misc app configs, managed verbatim from home/koki/dotfiles (were
# hand-maintained in ~/.config/). Packages themselves are in packages.nix.
# Read-only links for configs apps only read; writable copies (mutable.nix)
# for configs apps rewrite from their own settings UI.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  # Theme paths point into the package so they follow upgrades/GC instead
  # of a hard-coded /nix/store path.
  withStorePaths =
    file:
    builtins.replaceStrings
      [ "@btop@" "@rofi@" "@ctp-btop@" "@ctp-rofi@" ]
      [
        "${pkgs.btop}"
        "${pkgs.rofi}"
        "${config.catppuccin.sources.btop}"
        "${config.catppuccin.sources.rofi}"
      ]
      (builtins.readFile file);
in
{
  xdg.configFile = {
    "cava" = {
      source = ./dotfiles/cava;
      recursive = true;
    };
    "ghostty" = {
      source = ./dotfiles/ghostty;
      recursive = true;
    };
    "fastfetch/config.jsonc".source = ./dotfiles/fastfetch/config.jsonc;
    "nwg-dock-hyprland/style.css".source = ./dotfiles/nwg-dock-hyprland/style.css;
    "opencode/opencode.jsonc".source = ./dotfiles/opencode/opencode.jsonc;
    # Only config.yml — hosts.yml holds auth tokens and stays out of git.
    "gh/config.yml".source = ./dotfiles/gh/config.yml;
    "autostart/com.github.wwmm.easyeffects.desktop".source =
      ./dotfiles/autostart/com.github.wwmm.easyeffects.desktop;

    # btop: save_config_on_exit is off (the file is read-only); change
    # options in dotfiles/btop/btop.conf instead of the in-app menu.
    "btop/btop.conf".text = withStorePaths ./dotfiles/btop/btop.conf;
    "rofi/config.rasi".text = withStorePaths ./dotfiles/rofi/config.rasi;

    # ShojiWM user sources. package.json/tsconfig.json/node_modules are
    # regenerated by programs.shojiwm.initConfig on every activation, and it
    # skips seeding the template while src/index.tsx exists.
    "shojiwm/src" = {
      source = ./dotfiles/shojiwm/src;
      recursive = true;
    };
    "shojiwm/assets" = {
      source = ./dotfiles/shojiwm/assets;
      recursive = true;
    };
    "shojiwm/.editorconfig".source = ./dotfiles/shojiwm/.editorconfig;
  };

  koki.mutableFiles = {
    ".config/zed/settings.json" = ./dotfiles/zed/settings.json;
    ".config/Code/User/settings.json" = ./dotfiles/vscode/settings.json;
    # kilo appends permission grants as you approve them.
    ".config/kilo/kilo.jsonc" = ./dotfiles/kilo/kilo.jsonc;
    ".config/mimeapps.list" = ./dotfiles/mimeapps.list;

    ".config/fcitx5/config" = ./dotfiles/fcitx5/config;
    ".config/fcitx5/profile" = ./dotfiles/fcitx5/profile;
    ".config/fcitx5/conf/mozc.conf" = ./dotfiles/fcitx5/conf/mozc.conf;

    ".config/easyeffects/db/easyeffectsrc" = ./dotfiles/easyeffects/db/easyeffectsrc;
    ".config/easyeffects/db/bassEnhancerrc" = ./dotfiles/easyeffects/db/bassEnhancerrc;
    ".config/easyeffects/db/bassLoudnessrc" = ./dotfiles/easyeffects/db/bassLoudnessrc;
    ".config/easyeffects/db/expanderrc" = ./dotfiles/easyeffects/db/expanderrc;
    ".config/easyeffects/db/reverbrc" = ./dotfiles/easyeffects/db/reverbrc;
    ".local/share/easyeffects/output/kokisfault.json" = ./dotfiles/easyeffects/output/kokisfault.json;
  };
}
