# Hyprland user config. Compositor enablement is system-side
# (modules/desktop/hyprland.nix). The REAL session config is hyprland.lua
# (hyprland.lua + hyprpaper.conf, managed verbatim below) — HM's
# wayland.windowManager.hyprland stays OFF on purpose: enabling it would
# generate a competing hyprland.conf next to hyprland.lua.
# `unstable` arrives via flake extraSpecialArgs.
{
  config,
  lib,
  pkgs,
  unstable,
  ...
}:
let
  # Liquid Glass blur plugin (hyprnux/hyprglass). Must be built ENTIRELY
  # from unstable (stdenv + plugin builder + hyprland headers). Mixing
  # stable's stdenv/builder with unstable's hyprland links old
  # glibc/libstdc++ against new hyprland libs (missing GLIBC_2.43 /
  # GLIBCXX_3.4.35+), which segfaults Hyprland in
  # CPluginSystem::updateConfigPlugins on every login.
  hyprglass = unstable.callPackage ../../pkgs/hyprglass.nix {
    mkHyprlandPlugin = unstable.hyprlandPlugins.mkHyprlandPlugin;
    hyprland = unstable.hyprland;
  };
in
{
  home.packages = [ hyprglass ];

  home.sessionVariables = {
    # Directory containing Hyprland plugins (see hyprglass-path.lua which
    # loads the plugin via hl.plugin.load at config parse time).
    HYPR_PLUGIN_DIR = pkgs.symlinkJoin {
      name = "hyprland-plugins";
      paths = [ hyprglass ];
    };
  };

  # Bulletproof plugin load path: Nix interpolates the exact store path at
  # build time, so hyprland.lua doesn't depend on env vars or profiles.
  # Required by hyprland.lua via require("hyprglass-path") at the top.
  home.file.".config/hypr/hyprglass-path.lua".text = ''
    -- Generated by Nix (home/koki/hyprland.nix). Do not edit manually.
    hl.plugin.load("${hyprglass}/lib/libhyprglass.so")
  '';

  # Real session config, managed verbatim (was hand-maintained in
  # ~/.config/hypr/). Managed copies are byte-identical, so switching only
  # relinks them into the Nix store.
  home.file.".config/hypr/hyprland.lua".source = ./hyprland.lua;
  home.file.".config/hypr/hyprpaper.conf".source = ./hyprpaper.conf;
}
